### ISSUE TITLE
Add more position helper classes

### ISSUE THREAD

**Issue by rob-bar** [Crosscheck/Ocelot#146]
```scss
.abs {
  @include corner(absolute, "tl");
}

.rel {
  position: relative;
}

.fix {
  position: fixed;
}

.fullwidth {
  width: 100%;
}

.tac {
  text-align: center;
}

.tar {
  text-align: right;
}

.tal {
  text-align: left;
}
```
